### ISSUE TITLE
Support datapackage.yaml

### ISSUE THREAD

**Issue by ioggstream** [cldf/csvw#63]
## I expect

- to support datapackage.yaml files

## Instead

- it only works with JSON files

**Comment by xrotwang** [comment]
AFAICT, the [datapackage specification](https://specs.frictionlessdata.io/data-package/#specification) says

> A Data Package descriptor MUST be a valid JSON object

Now, I'm aware of [the discussion](https://github.com/frictionlessdata/specs/issues/292) about allowing yaml as alternative descriptor format, but the support for datapackages in this package is more a proof-of-concept feature and will likely never be complete (e.g. support anything beyond tabular data resources). So rather than expecting yaml support from `csvw`, I'd hope for a yaml-to-json converter in datapackages tooling once yaml is officially recognized as descriptor doemat.

**Comment by ioggstream** [comment]
Hi @xrotwang ! I found on this FAQ that frictionless works both on JSON and YAML. If you want, I can provide a PR but if you confirm this is wontfix, that's fine too :) Have a nice day, R.

 https://framework.frictionlessdata.io/docs/faq/#why-am-i-getting-the-error-cannot-extract-tabular-data-from-json

**Comment by xrotwang** [comment]
If you create the datapackage descriptor via `frictionless describe`, then passing the `--json` option would be all that's needed to get JSON metadata. And I think I'd rather de-emphasize the datapackage support here, than having to deal with two specs in this one package :)
